export interface HojaVidaAdmin {
    direccion: string;
    estadoUsuario?: number;
    telefonoUsuario?: string;
    idEps?: number;
    tipo_documento: 'CC' | 'TI' | 'RC' | 'CE';
    sexo?: 'M' | 'F';
    nacionalidad?: string;
    pais?: string;
    fecha_nacimiento?: Date;
    lugar_nacimiento?: string;
    alergias?: string;
    discapacidad?: string;
    contacto_emergencia_nombre?: string;
    contacto_emergencia_parentesco?: string;
    contacto_emergencia_telefono?: string;
    contacto_emergencia_correo?: string;
    cargo: string;
    fechaIngreso?: Date;
    tipoContrato?: 'Indefinido' | 'Fijo' | 'Prestación de servicios';
    salarioBasico?: number;
    bonificaciones?: number;
    deducciones?: number;
    fechaPago?: Date;
    metodoPago?: string;
    vacacionesPendientes?: number;
    diasIncapacidad?: number;
    historialPagos?: string;
    autorizacionesEspeciales?: string;
    fechaTerminacion?: Date;
    motivoTerminacion?: string;
    observaciones?: string;
}